import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets:['latin'],
  weight:['400']
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        {/* <QueryClientProvider> */}
        <div className={`${poppins.className}`}>
        {children}
        </div>

        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
