import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "./components/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        <QueryClientProvider client={QueryProvider}>
          <div className={`${poppins.className}`}>{children}</div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
